server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/movie_collection
    username: movie_user
    password: movie_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html

app:
  jwt:
    secret: movie-collection-dev-secret-change-me
  admin:
    email: admin@movie.local
    password: admin123
